[package]
name = "junk-unav"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
bevy_core = "0.15.1"
bevy_ecs = "0.15.1"
bevy_prototype_lyon = "0.13.0"
nanoid = "0.4.0"
noise = "0.9.0"
rand = "0.8.5"
